#!/usr/bin/env node

const clear = require("clear");
const chalk = require("chalk");
const prompts = require("prompts");
const fs = require("fs");
const cmd = require("node-cmd");

///////////////////////////////////////// Asking for INFO

const questions = [
    {
        type: "text",
        name: "givenProject",
        message: "Project's name :"
    },
    {
        type: "text",
        name: "givenDescription",
        message: "Description :"
    },
    {
        type: "text",
        name: "givenFolder",
        message: "Folder :"
    },
    {
        type: "text",
        name: "givenCommand",
        message: "Terminal command :"
    }
];

///////////////////////////////////////// Getting INFO

var coffee = async () => {

    const response = await prompts(questions);
    var thatDescription= response.givenDescription;
    var thatProject = response.givenProject;
    var thatFolder = response.givenFolder;
    var thatCommand = response.givenCommand;

///////////////////////////////////////// Creating FILE

    fs.writeFile(`${thatProject}_GAC`,

`#!/bin/bash
\n#Description : ${thatDescription}
\nclear;
echo "
         {
      {   }
       }_{ __{
    .-{   }   }-.
   (   }     {   )
   |'-.._____..-'|
   |             :--.     
   |            (__  |           
   |             |)  )        -> Grab a coffee, it's loading. 
   |             /  /   
   |            (  /
   |             y'
    '-.._____..-' ''
\n\n\n
"
echo -n "Locating '${thatFolder}' folder "; while true;do echo -n .;sleep 1;done &
\ncd $(find ~/ -name "${thatFolder}")
\nkill $!; trap 'kill $!' SIGTERM
\necho done;
\nclear;
\n${thatCommand};
\n\n\n\n\n\n\n#Proudly generated by © Grab a coffee 2019.`,

    function (err) {
    if (err) throw err;
    console.log(chalk.bgGreen('\n\nFile was successfully created.\n'));
    });

///////////////////////////////////////// Converting FILE

    cmd.run(`chmod 700 ${thatProject}_GAC`);
};

///////////////////////////////////////// DONE

clear();
coffee();